"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const ArgumentTypes = {
    Equal: "equal",
    NotEqual: "notEqual",
    IsNull: "isNull",
    IsNotNull: "isNotNull",
    In: "in",
    NotIn: "notIn",
    Contains: "contains",
    NotContains: "notContains",
    StartsWith: "startsWith",
    NotStartsWith: "notStartsWith",
    EndsWith: "endsWith",
    NotEndsWith: "notEndsWith",
    Like: "like",
    NotLike: "notLike",
    GreaterThan: "greaterThan",
    LessThan: "lessThan",
    GreaterThanOrEqual: "greaterThanOrEqual",
    LessThanOrEqual: "lessThanOrEqual",
    CreateArgument: "createArgument",
    CreateOrUpdateArgument: "createOrUpdateArgument",
    CreateSubModel: "createSubModel",
    CreateOrUpdateSubModel: "createOrUpdateSubModel",
    CreateSubCollection: "createSubCollection",
    CreateOrUpdateSubCollection: "createOrUpdateSubCollection",
    UpdateSetter: "updateSetter",
};
exports.default = ArgumentTypes;
